version: '2'
services:
  api:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-api:${MONTAGU_API_VERSION}
    depends_on:
      - db
  reporting_api:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-reporting-api:${MONTAGU_REPORTING_API_VERSION}
    volumes:
      - orderly_volume:/orderly
      # If use_real_passwords is true then emails will be really sent, and this
      # volume will remain empty. Otherwise emails are written to disk here.
      - emails:/montagu/emails 
  db:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-db:${MONTAGU_DB_VERSION}
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/pgdata
  contrib:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-contrib-portal:${MONTAGU_CONTRIB_PORTAL_VERSION}
    depends_on:
      - api
  admin:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-admin-portal:${MONTAGU_ADMIN_PORTAL_VERSION}
    depends_on:
      - api
  report:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-report-portal:${MONTAGU_REPORT_PORTAL_VERSION}
    depends_on:
      - api
      - reporting_api
  proxy:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-reverse-proxy:${MONTAGU_PROXY_VERSION}
    ports:
      - "${MONTAGU_PORT}:${MONTAGU_PORT}"
      - 80:80
    depends_on:
      - api
      - reporting_api
      - admin
      - contrib
      - report
    command: ${MONTAGU_PORT} ${MONTAGU_HOSTNAME}

volumes:
  db_volume:
  orderly_volume:
  emails:
