version: '2'
services:
  api:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-api:${MONTAGU_API_VERSION}
    depends_on:
      - db
  db:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-db:${MONTAGU_DB_VERSION}
    ports:
      - "5432:5432"
  contrib:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-contrib-portal:${MONTAGU_CONTRIB_VERSION}
    depends_on:
      - api
  admin:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-admin-portal:${MONTAGU_ADMIN_VERSION}
    depends_on:
      - api
  proxy:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-reverse-proxy:${MONTAGU_PROXY_VERSION}
    ports:
      - "443:443"
    depends_on:
      - api
      - admin
      - contrib

